apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: apicontainer
        image: egedocker/fastapi-repo:microservice-latest
        resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
        ports: 
        - name: http
          containerPort: 3000
